Compatibility with Laravel 10.x
thomasjohnkane/snooze pull request #109
Opened 2023-02-21 18:58 UTC by colq2

This PR bumps the dependencies so the package can be used with laravel 10.x

2023-02-21 21:38 UTC, atymic requested changes

2023-02-21 21:38 UTC, atymic commented on .github/workflows/php.yml
> +        laravel-version: ['^6.0', '^7.0', '^8.0', '^9.0', '^10.0']
Drop everything below 8 please

2023-02-21 21:38 UTC, atymic commented on .github/workflows/php.yml
> +        php-versions: ['7.3', '7.4', '8.0', '8.1']
```suggestion
        php-versions: ['8.0', '8.1', '8.2']
```

2023-02-21 21:38 UTC, atymic commented on .github/workflows/php.yml
> +          - laravel-version: ^10.0
No need

2023-02-21 21:38 UTC, atymic commented on .github/workflows/php.yml
>            - laravel-version: ^6.0
Delete 6 and 7 fom here

2023-02-21 21:38 UTC, atymic commented on composer.json
> +        "php": ">8.1",
Lets keep > 8.0 support please

2023-02-21 21:38 UTC, atymic commented on composer.json
> +        "illuminate/support": "^10.0"
Same here, 8+ for laravel and other deps

2023-02-22 10:07 UTC, colq2 commented
@atymic thank you for reviewing this! I addressed your review. Just saw that there is another PR from laravel-shift.

2023-02-26 13:36 UTC, colq2 commented
@atymic is there anything else that is holding this back? I am happy to help

2023-02-26 20:52 UTC, atymic approved these changes

2023-02-26 21:34 UTC, merged